name: Build & upload APK to TestApp.io

on:
  workflow_dispatch:
  push:
    branches: 
      - main
      - develop

jobs:
  unit-test: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      
      - name: "Set up JDK"
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: "Lancer les test"
        run: ./gradlew testDebugUnitTest
    
  build:
    name: Build and upload to TestApp.io
    needs: unit-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Determiner le type de build
        id: build-type
        run: |
          if [[ "${{ github.ref_name }}" == "main" ]]; then
            echo "BUILD_TYPE=Release" >> $GITHUB_OUTPUT
          else
            echo "BUILD_TYPE=Debug" >> $GITHUB_OUTPUT
          fi

      # Ce step doit se lancer si le trigger se fait sur la branche develop
      - name: Build debug
        # conditionner ce step
        if: steps.build-type.outputs.BUILD_TYPE == 'Debug'
        run: ./gradlew assembleDebug

      # Ce step doit se lancer si le trigger se fait sur la branche main
      - name: Build Release
        # conditionner ce step
        if: steps.build-type.outputs.BUILD_TYPE == 'Release'
        run: ./gradlew assembleRelease
